% SAP_lisst200x02059
%
% Reads sensor information and data from
% WAP-extracted files identified in cfg as having the
% sensor ID "lisst200x02059", as called by SAP_lvl_1.
%
% USAGE: lisst200x02059 = SAP_lisst200x02059(cfg)
%
% INPUT
%   cfg - a single row of configuration table as a structure array with
%   scalar fields
%
% OUTPUT
%   lisst200x02059 - struct array with data and sensor information
%
% M. McFarland 2024-05-20
% Inspired by: N. Stockley
%

%% Declare function
function lisst200x02059 = SAP_lisst200x02059(cfg)

%% Processing documentation
% Documents the action happening, the full path and file name of the
% current function, and the date/time of execution. This information can be
% referenced to determine when this function was executed and which version
% was used.
% lisst200x02059.info.documentation(1,1) = {'PROCESS'};
% lisst200x02059.info.documentation(1,2) = {'FILE NAME'};
% lisst200x02059.info.documentation(1,3) = {'DATE'};
% lisst200x02059.info.documentation(1,4) = {'SOURCE'};
% lisst200x02059.info.documentation(2,1) = {'Sensor ID:'};
% lisst200x02059.info.documentation{2,2} = mfilename('fullpath');
% lisst200x02059.info.documentation{2,3} = datestr(now,31);
% lisst200x02059.info.documentation(3,1) = {'Extracted file:'};
% lisst200x02059.info.documentation{3,2} = horzcat(cd,'\',cfg_row{3});

%% Sensor information
% Writes information about the sensor to the structure field. This
% information will be called in later processing.
lisst200x02059.info.type = 'lisst200x'; % category for level 2 processing
lisst200x02059.info.sensor_id = 'lisst200x02059';
lisst200x02059.info.wavelength_nm = 670;
lisst200x02059.info.pathlength_m = 0.025;
lisst200x02059.info.timeoffset = cfg.timeoffset;
lisst200x02059.info.depthoffset = cfg.depthoffset;
lisst200x02059.info.calrow = cfg.calrow;
lisst200x02059.info.mode = cfg.mode;

%% Import data
% Imports data from extracted archive file.
pth = [cfg.path filesep cfg.fname];
fid = fopen(pth);
import = textscan(fid,'%n %s','Delimiter','\t');
fclose(fid);
real_data_length = size(import{1,1},1);
text_header = {};
count_data = {};
good_data = [];
for x = 1:real_data_length
    line_split = regexp(import{1,2}(x,1),',','split');
    switch size(line_split{1,1},2)
        case 1
            text_header_size = size(text_header,1);
            text_header{text_header_size+1,1} = import{1,1}(x,1); %#ok<*AGROW>
            text_header{text_header_size+1,2} = import{1,2}(x,1);
        case 2
            count_data_size = size(count_data,1);
            count_data{count_data_size+1,1} = import{1,1}(x,1);
            count_data{count_data_size+1,2} = str2double(line_split{1,1}{1,1});
            count_data{count_data_size+1,3} = str2double(line_split{1,1}{1,2}(1:end-1));
        case 59
            good_data_size = size(good_data,1);
            good_data(good_data_size+1,1) = import{1,1}(x,1);
            good_data(good_data_size+1,2:60) = str2double(line_split{1,1});
    end
end
count_data = cell2mat(count_data);
lisst200x02059.info.text_header = text_header;
lisst200x02059.info.count_data = count_data;
lisst200x02059.raw = good_data;

%% Data array
% Writes data and the information entered in LOG_ARRAY.ARCLOG into a
% structure field for this sensor. Uses the calibration row value to
% write data from the specified calibration. Also writes values
% previously calculated in this function.
lisst200x02059.info.header = {'Time','ms';...
    'Ring1','counts';...
    'Ring2','counts';...
    'Ring3','counts';...
    'Ring4','counts';...
    'Ring5','counts';...
    'Ring6','counts';...
    'Ring7','counts';...
    'Ring8','counts';...
    'Ring9','counts';...
    'Ring10','counts';...
    'Ring11','counts';...
    'Ring12','counts';...
    'Ring13','counts';...
    'Ring14','counts';...
    'Ring15','counts';...
    'Ring16','counts';...
    'Ring17','counts';...
    'Ring18','counts';...
    'Ring19','counts';...
    'Ring20','counts';...
    'Ring21','counts';...
    'Ring22','counts';...
    'Ring23','counts';...
    'Ring24','counts';...
    'Ring25','counts';...
    'Ring26','counts';...
    'Ring27','counts';...
    'Ring28','counts';...
    'Ring29','counts';...
    'Ring30','counts';...
    'Ring31','counts';...
    'Ring32','counts';...
    'Ring33','counts';...
    'Ring34','counts';...
    'Ring35','counts';...
    'Ring36','counts';...
    'LaserTransmissionSensor','counts';...
    'SupplyVoltage','0.01 V/count';...
    'ExternalAnalogInput1','10^-4 V/count';...
    'LaserReference','counts';...
    'Depth','0.01 m/count + 10 m';...
    'Temperature','1 m degC/count + 5 degC';...
    'Year','';...
    'Month','';...
    'DayOfMonth','';...
    'Hour','';...
    'Minute','';...
    'Second','';...
    'ExternalAnalogInput2','10^-4 V/count';...
    'SauterMeanDiamter','0.1 um/count';...
    'TotalVolumeConcentration','0.1 ppm/count';...
    'RelativeHumidity','%';...
    'AccelerometerX','counts';...
    'AccelerometerY','counts';...
    'AccelerometerZ','counts';...
    'RawPressure1','most significant bit';...
    'RawPressure2','least significant 16 bits';...
    'AmbientLight','counts';...
    'NotUsed',''};
% lisst200x02059.data.data.mode = cfg_row{5};
% lisst200x02059.data.data.companion_archive = cfg_row{6};
% lisst200x02059.data.data.companion_sensor = cfg_row{7};
% lisst200x02059.data.data.reference_ctd = cfg_row{8};
% lisst200x02059.data.data.calrow = cfg_row{10};
% lisst200x02059.data.data.bin_mode = cfg_row{11};
% lisst200x02059.data.data.timeoffset = cfg_row{12};
% lisst200x02059.data.data.time_bins = cfg_row{13};
% lisst200x02059.data.data.depthoffset = cfg_row{14};
% lisst200x02059.data.data.depth_bins = cfg_row{15};

load('lisst200x02059_cal.mat')
lisst200x02059.info.cal.zsc  = lisst200x02059_cal.zsc(cfg.calrow,:);
lisst200x02059.info.cal.fzs  = lisst200x02059_cal.fzs;
lisst200x02059.info.cal.dcal = lisst200x02059_cal.dcal;
lisst200x02059.info.cal.VCC  = lisst200x02059_cal.VCC;

% lisst200x02059.info.cal.date = lisst200x02059_cal{cfg.calrow,1}; %#ok<*IDISVAR,USENS>
% lisst200x02059.info.cal.constants = lisst200x02059_cal{cfg.calrow,3};
% lisst200x02059.info.cal.dark_counts = lisst200x02059_cal{cfg.calrow,4};
% lisst200x02059.info.cal.zscat = lisst200x02059_cal{cfg.calrow,5};

%% Load calibration data
% Loads the sensor calibration data into the function workspace.
%         load('lisst200x02059_cal.mat'); %#ok<*LOAD>

% %% Calculate sampling rate (Hz)
% % Calculates the data sampling rate by:
% %
% % $$sampling_-rate = \frac{total_-samples}{\frac{end_-time-start_-time}{1000}}$$
% %
% % The elapsed time must be divided by 1000 to convert from data time in
% % milliseconds to seconds. The rate will be approximate when any data
% % interruption occurs, resulting in elapsed time without samples.
% elapsed_time = (good_data(end,1) - good_data(1,1))/1000;
% total_samples = length(good_data(:,1));
% sampling_rate = total_samples/elapsed_time;
% lisst200x02059.info.sampling_rate = sampling_rate;
